name: public-pool-bitcoin
services:
  app:
    container_name: public-pool-bitcoin
    image: theretromike/nodes:bitcoin
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-bitcoin/data:/root/.bitcoin
    ports:
      - "7004:7004"
      - "9004:9004"
      - "8333:8333"
    command: "/usr/bin/bitcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://0.0.0.0:7004 -rpcbind=0.0.0.0 -rpcport=9004 -rpcallowip=0.0.0.0/0 -port=8333 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-bitcoin
  category: Public Pool
  title:
    en_US: Bitcoin (BTC) Node
  tagline:
    en_US: Bitcoin pruned node for Public Pool.
  description:
    en_US: Bitcoin node with RPC and ZMQ enabled.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/bitcoin/icon.png
  port_map: "9004"
