name: public-pool-bitcoin-silver
services:
  app:
    container_name: public-pool-bitcoin-silver
    image: theretromike/nodes:bitcoinsilver
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-bitcoin-silver/data:/root/.bitcoinsilver
    ports:
      - "7015:7015"
      - "9015:9015"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-bitcoin-silver
  category: Public Pool
  title:
    en_US: BTCS Node
  tagline:
    en_US: BTCS node for Public Pool.
  description:
    en_US: BTCS node.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/bitcoin-silver/icon.png
  port_map: "9015"
