name: public-pool-zec
services:
  app:
    container_name: public-pool-zec
    image: theretromike/nodes:zcash
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-zcash/data:/root/.zcash
    ports:
      - "7036:7036"
      - "9036:9036"
      - "8233:8233"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-zcash
  category: Public Pool
  title:
    en_US: ZEC Node
  tagline:
    en_US: ZEC node.
  description:
    en_US: ZEC node.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/zcash/icon.png
  port_map: "9036"
