name: public-pool-digibyte
services:
  app:
    container_name: public-pool-digibyte
    image: theretromike/nodes:digibyte
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-digibyte/data:/root/.digibyte
    ports:
      - "7001:7001"
      - "9001:9001"
      - "12024:12024"
    entrypoint: /usr/bin/digibyted
    command: "-printtoconsole -server -algo=sha256d -prune=550 -wallet=default -zmqpubhashblock=tcp://0.0.0.0:7001 -rpcbind=0.0.0.0 -rpcport=9001 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-digibyte
  category: Public Pool
  title:
    en_US: Digibyte (DGB) Node
  tagline:
    en_US: Digibyte node for Public Pool.
  description:
    en_US: Digibyte node with RPC and ZMQ enabled.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/digibyte/icon.png
  port_map: "9001"
