name: public-pool-auroracoin
services:
  app:
    container_name: public-pool-auroracoin
    image: local/auroracoin:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-auroracoin/data:/root/.auroracoin
    ports:
      - "7021:7021"
      - "9021:9021"
      - "12340:12340"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-auroracoin
  category: Public Pool
  title:
    en_US: Auroracoin (AUR) Node
  tagline:
    en_US: Auroracoin node for Public Pool.
  description:
    en_US: Auroracoin node for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/auroracoin/icon.png
  port_map: "9021"
