name: public-pool-ergo
services:
  app:
    container_name: public-pool-ergo
    image: local/ergo:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-ergo/data:/root/.ergo
    ports:
      - "9051:9051"
      - "9030:9030"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-ergo
  category: Public Pool
  title:
    en_US: Ergo (ERG) Node
  tagline:
    en_US: Ergo node for Public Pool.
  description:
    en_US: Ergo node for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/ergo/icon.png
  port_map: "9051"
