name: public-pool-miningcore-webui
services:
  app:
    container_name: public-pool-miningcore-webui
    image: theretromike/miningcorewebui:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /DATA/AppData/public-pool-miningcore-webui/data:/app/miningcore
    ports:
      - "81:8080"
    environment:
      - API_BASE_URL=http://host.docker.internal:4000/api
      - MININGCORE_HOST=host.docker.internal
      - PLATFORM=ZIMAOS
      - POOL_NAME=public-pool-btc.ru
      - POSTGRES_DATABASE=miningcore
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PASSWORD=miningcore
      - POSTGRES_USER=miningcore
      - PUID=1000
      - STRATUM_HOST=host.docker.internal
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-miningcore-webui
  category: Public Pool
  title:
    en_US: Miningcore Web UI
  tagline:
    en_US: Pool web interface.
  description:
    en_US: Miningcore Web UI for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/miningcore-webui/icon.png
  port_map: "81"
