name: public-pool-peercoin
services:
  app:
    container_name: public-pool-peercoin
    image: theretromike/nodes:peercoin
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-peercoin/data:/root/.peercoin
    ports:
      - "7012:7012"
      - "9012:9012"
      - "9901:9901"
    command: "/usr/bin/peercoind -printtoconsole -server -wallet=default -zmqpubhashblock=tcp://0.0.0.0:7012 -rpcbind=0.0.0.0 -rpcport=9012 -rpcallowip=0.0.0.0/0 -port=9901 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-peercoin
  category: Public Pool Coins
  title:
    en_US: Peercoin (PPC) Node
  tagline:
    en_US: Peercoin node for Public Pool.
  description:
    en_US: Peercoin daemon node with RPC and ZMQ enabled.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/peercoin/icon.png
  port_map: "9012"
