name: public-pool-kaspa
services:
  app:
    container_name: public-pool-kaspa
    image: theretromike/nodes:kaspa
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-kaspa/data:/root/.kaspa
    ports:
      - "16110:16110"
      - "17110:17110"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-kaspa
  category: Public Pool
  title:
    en_US: Kaspa (KAS) Node
  tagline:
    en_US: Kaspa node for Public Pool.
  description:
    en_US: Kaspa node for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/kaspa/icon.png
  port_map: "16110"
