name: public-pool-bitcoin-cash
services:
  app:
    container_name: public-pool-bitcoin-cash
    image: theretromike/nodes:bitcoincash
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-bitcoin-cash/data:/root/.bitcoin
    ports:
      - "7002:7002"
      - "9002:9002"
      - "8334:8334"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-bitcoin-cash
  category: Public Pool
  title:
    en_US: Bitcoin Cash (BCH) Node
  tagline:
    en_US: Bitcoin Cash Cryptocurrency Node.
  description:
    en_US: Bitcoin Cash Cryptocurrency Node.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/bitcoin-cash/icon.png
  port_map: "9002"
