name: public-pool-bitcoin-cash
services:
  app:
    container_name: public-pool-bitcoin-cash
    image: zquestz/bitcoin-cash-node:29.0.0
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-bitcoin-cash/data:/data
    ports:
      - "9002:8332"
      - "8334:8333"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-bitcoin-cash
  category: Public Pool
  title:
    en_US: Bitcoin Cash (BCH) Node
  tagline:
    en_US: Bitcoin Cash node.
  description:
    en_US: Bitcoin Cash node.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/bitcoin-cash/icon.png
  port_map: "9002"
