name: public-pool-komodo
services:
  app:
    container_name: public-pool-komodo
    image: theretromike/nodes:komodo
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-komodo/data:/root/.komodo
    ports:
      - "7035:7035"
      - "9035:9035"
      - "7770:7770"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-komodo
  category: Public Pool
  title:
    en_US: Komodo Node
  tagline:
    en_US: Komodo node.
  description:
    en_US: Komodo node.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/komodo/icon.png
  port_map: "9035"
