name: public-pool-flux
services:
  app:
    container_name: public-pool-flux
    image: local/flux:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-flux/data:/root/.flux
    ports:
      - "9161:9161"
      - "16125:16125"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-flux
  category: Public Pool
  title:
    en_US: Flux (FLUX) Node
  tagline:
    en_US: Flux node for Public Pool.
  description:
    en_US: Flux node for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/flux/icon.png
  port_map: "9161"
