name: public-pool-ravencoin
services:
  app:
    container_name: public-pool-ravencoin
    image: dramirezrt/ravencoin-core-server:v4.6.1
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-ravencoin/data:/root/.raven
    ports:
      - "8088:8080"
      - "38766:38766"
      - "38767:38767"
      - "28332:28332"
      - "28333:28333"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-ravencoin
  category: Public Pool
  title:
    en_US: Ravencoin (RVN) Node
  tagline:
    en_US: Ravencoin node for Public Pool.
  description:
    en_US: Ravencoin node with ZMQ support.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/ravencoin/icon.png
  port_map: "8088"
