name: public-pool-ravencoin
services:
  app:
    container_name: public-pool-ravencoin
    image: theretromike/nodes:ravencoin
    restart: always
    volumes:
      - /DATA/AppData/public-pool-ravencoin/data:/root/.raven
    ports:
      - "7010:7010"
      - "9010:9010"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-ravencoin
  category: Public Pool
  title:
    en_US: Ravencoin Node
  tagline:
    en_US: Ravencoin node.
  description:
    en_US: Ravencoin node.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/ravencoin/icon.png
  port_map: "9010"
