name: public-pool-postgres-legacy
services:
  app:
    container_name: public-pool-postgres-legacy
    image: postgres:17.4
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-postgres-legacy/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  store_app_id: public-pool-postgres-legacy
  category: Public Pool
  title:
    en_US: PostgreSQL
  tagline:
    en_US: PostgreSQL database for Public Pool.
  description:
    en_US: PostgreSQL database service.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/postgres/icon.png
  port_map: "5432"
