name: public-pool-miningcore
services:
  app:
    container_name: public-pool-miningcore
    image: theretromike/miningcore:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-miningcore/coins.json:/app/build/coins.json
      - /DATA/AppData/public-pool-miningcore/config.json:/app/config.json
      - /DATA/AppData/public-pool-miningcore/logs:/app/logs
    ports:
      - "4000:4000"
      - "6001-6025:6001-6025"
      - "6201-6225:6201-6225"
      - "6301-6325:6301-6325"
      - "6401-6425:6401-6425"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-miningcore
  category: Public Pool
  title:
    en_US: Miningcore
  tagline:
    en_US: Mining pool backend.
  description:
    en_US: Miningcore backend for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/miningcore/icon.png
  port_map: "4000"
