name: public-pool-monero
services:
  app:
    container_name: public-pool-monero
    image: theretromike/nodes:monero
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-monero/data:/root/.bitmonero
    ports:
      - "7109:7009"
      - "9109:9009"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-monero
  category: Public Pool Coins
  title:
    en_US: Monero (XMR) Node
  tagline:
    en_US: Monero node.
  description:
    en_US: Monero node for Public Pool.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/monero/icon.png
  port_map: "9109"
