name: public-pool-dogecoin
services:
  app:
    container_name: public-pool-dogecoin
    image: theretromike/nodes:dogecoin
    restart: unless-stopped
    volumes:
      - /DATA/AppData/public-pool-dogecoin/data:/root/.dogecoin
    ports:
      - "7003:7003"
      - "9003:9003"
    command: "/usr/bin/dogecoind -printtoconsole -server -prune=2200 -wallet=default -zmqpubhashblock=tcp://0.0.0.0:7003 -rpcbind=0.0.0.0 -rpcport=9003 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  store_app_id: public-pool-dogecoin
  category: Public Pool Coins
  title:
    en_US: Dogecoin (DOGE) Node
  tagline:
    en_US: Dogecoin pruned node for Public Pool.
  description:
    en_US: Dogecoin daemon node with RPC and ZMQ enabled.
  developer: Public Pool
  author: Public Pool
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/dogecoin/icon.png
  port_map: "9003"
