name: monerowallet
services:
  app:
    container_name: app-monero-wallet
    image: theretromike/nodes:monero
    restart: always
    volumes:
      - /media/ZimaOS-HD/NodeData/app-monero-wallet:/wallet
    ports:
      - "18182:18082"
    command:
      - /bin/sh
      - -lc
      - >
        exec monero-wallet-rpc
        --wallet-file /wallet/pool
        --password poolwalletpass
        --daemon-address 192.168.0.175:9109
        --daemon-ssl disabled
        --rpc-bind-ip 0.0.0.0
        --rpc-bind-port 18082
        --rpc-ssl disabled
        --confirm-external-bind
        --disable-rpc-login
        --trusted-daemon
        --log-level 1
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Monero Cryptocurrency Wallet RPC
  tagline:
    en_us: Monero Cryptocurrency Wallet RPC
  developer: Retro Mike
  author: Retro Mike
  icon: https://raw.githubusercontent.com/Sert1985n/public-pool-store-clean/main/Apps/monero-wallet/icon.png
  thumbnail: ""
  title:
    en_us: Monero (XMR) Wallet
  category: RetroMike
  port_map: "18182"
